import { TestRun, Failure, Protocol, Fixture } from './types'

export function downloadFile(content: string, filename: string, mime = 'text/plain') {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

function csvRow(cells: (string | number | null | undefined)[]): string {
  return cells.map(c => {
    const s = String(c ?? '')
    return s.includes(',') || s.includes('"') || s.includes('\n') ? `"${s.replace(/"/g, '""')}"` : s
  }).join(',')
}

export function testRunsToCSV(testRuns: TestRun[], protocols: Protocol[], fixtures: Fixture[]): string {
  const header = csvRow(['ID', 'Protocol', 'Revision', 'Unit ID', 'Operator', 'Fixture', 'Date', 'Result', 'Observations'])
  const rows = testRuns.map(tr => {
    const proto = protocols.find(p => p.id === tr.protocol_id)
    const fix = fixtures.find(f => f.id === tr.fixture_id)
    return csvRow([
      tr.id,
      proto?.name ?? tr.protocol_id,
      tr.protocol_revision,
      tr.unit_id,
      tr.operator,
      fix?.name ?? tr.fixture_id,
      tr.date,
      tr.result,
      tr.observations,
    ])
  })
  return [header, ...rows].join('\n')
}

export function failuresToCSV(failures: Failure[]): string {
  const header = csvRow([
    'ID', 'Test Run', 'Failure Mode', 'Severity', 'Status',
    'Disposition', 'Owner', 'Opened', 'Closed', 'Suspected Cause', 'Corrective Action',
  ])
  const rows = failures.map(f => csvRow([
    f.id, f.test_run_id, f.failure_mode, f.severity, f.status,
    f.disposition, f.owner, f.opened_date, f.closed_date ?? '',
    f.suspected_cause, f.corrective_action,
  ]))
  return [header, ...rows].join('\n')
}

export function testRunToMarkdown(
  tr: TestRun,
  protocol: Protocol | undefined,
  fixture: Fixture | undefined,
  failures: Failure[],
): string {
  const lines: string[] = []
  lines.push(`# Test Run Report: ${tr.id}`)
  lines.push('')
  lines.push(`**Protocol:** ${protocol?.name ?? tr.protocol_id}  `)
  lines.push(`**Revision:** ${tr.protocol_revision}  `)
  lines.push(`**Unit ID:** ${tr.unit_id}  `)
  lines.push(`**Operator:** ${tr.operator}  `)
  lines.push(`**Fixture:** ${fixture?.name ?? tr.fixture_id}  `)
  lines.push(`**Date:** ${tr.date}  `)
  lines.push(`**Result:** ${tr.result.toUpperCase().replace('_', ' ')}`)
  lines.push('')

  lines.push('## Measurements')
  lines.push('')
  lines.push('| Parameter | Measured | Unit | Within Spec |')
  lines.push('|-----------|----------|------|-------------|')
  tr.measurements.forEach(m => {
    lines.push(`| ${m.parameter} | ${m.value} | ${m.unit} | ${m.within_spec ? 'Yes' : 'No'} |`)
  })
  lines.push('')

  if (protocol?.acceptance_criteria?.length) {
    lines.push('## Acceptance Criteria')
    lines.push('')
    lines.push('| Parameter | Unit | Min | Max | Nominal |')
    lines.push('|-----------|------|-----|-----|---------|')
    protocol.acceptance_criteria.forEach(ac => {
      lines.push(`| ${ac.parameter} | ${ac.unit} | ${ac.min ?? '-'} | ${ac.max ?? '-'} | ${ac.nominal ?? '-'} |`)
    })
    lines.push('')
  }

  if (tr.observations) {
    lines.push('## Observations')
    lines.push('')
    lines.push(tr.observations)
    lines.push('')
  }

  if (failures.length > 0) {
    lines.push('## Linked Failures')
    lines.push('')
    failures.forEach(f => {
      lines.push(`### ${f.id}: ${f.failure_mode}`)
      lines.push('')
      lines.push(`- **Severity:** ${f.severity}`)
      lines.push(`- **Status:** ${f.status}`)
      lines.push(`- **Owner:** ${f.owner}`)
      lines.push(`- **Suspected Cause:** ${f.suspected_cause}`)
      lines.push(`- **Corrective Action:** ${f.corrective_action}`)
      lines.push('')
    })
  }

  lines.push('---')
  lines.push('')
  lines.push('*Generated by TestBench Tracker (demo environment)*')
  lines.push('')
  lines.push('> **Note:** This is a demonstration tool. Production usage requires authentication, formal validation, access control, and controlled document management per applicable quality standards.')
  return lines.join('\n')
}
