import { Protocol, TestRun, Fixture, Failure } from './types'

export const MOCK_PROTOCOLS: Protocol[] = [
  {
    id: 'proto-001',
    name: 'Pressure Relief Valve Functional Test',
    revision: 'B',
    owner: 'M. Torres',
    equipment_required: [
      'Hydraulic pressure source (0-500 PSI)',
      'Calibrated pressure gauge (+/-0.5% FS)',
      'High-pressure tubing assembly (rated 600 PSI)',
      'Catch basin (2 gal minimum rated capacity)',
    ],
    fixture_required: 'FIX-001',
    acceptance_criteria: [
      { id: 'ac-001-1', parameter: 'Relief pressure setpoint', unit: 'PSI', min: 290, max: 310, nominal: 300 },
      { id: 'ac-001-2', parameter: 'Reseat pressure', unit: 'PSI', min: 250, max: 285, nominal: 270 },
      { id: 'ac-001-3', parameter: 'Flow rate at setpoint', unit: 'GPM', min: 2.0, max: 4.5, nominal: 3.0 },
      { id: 'ac-001-4', parameter: 'Leak rate after reseat', unit: 'mL/min', min: 0, max: 5.0 },
    ],
    status: 'active',
    created_at: '2025-01-15T08:00:00Z',
    updated_at: '2025-06-10T14:22:00Z',
  },
  {
    id: 'proto-002',
    name: 'Temperature Sensor Calibration Verification',
    revision: 'C',
    owner: 'R. Patel',
    equipment_required: [
      'Reference thermocouple (NIST traceable, Class A)',
      'Dry block calibration bath',
      'Data acquisition module (16-bit)',
    ],
    fixture_required: 'FIX-002',
    acceptance_criteria: [
      { id: 'ac-002-1', parameter: 'Accuracy at -20 C', unit: 'C', min: -0.5, max: 0.5, nominal: 0 },
      { id: 'ac-002-2', parameter: 'Accuracy at 25 C', unit: 'C', min: -0.5, max: 0.5, nominal: 0 },
      { id: 'ac-002-3', parameter: 'Accuracy at 70 C', unit: 'C', min: -0.5, max: 0.5, nominal: 0 },
      { id: 'ac-002-4', parameter: 'Response time (63% step)', unit: 's', min: 0, max: 30, nominal: 20 },
    ],
    status: 'active',
    created_at: '2025-02-01T09:00:00Z',
    updated_at: '2025-08-15T11:30:00Z',
  },
  {
    id: 'proto-003',
    name: 'Compressor Leak Test',
    revision: 'A',
    owner: 'D. Kim',
    equipment_required: [
      'Electronic refrigerant leak detector',
      'Nitrogen supply with two-stage regulator',
      'Pressure decay test unit (resolution 0.1 PSI)',
    ],
    fixture_required: 'FIX-003',
    acceptance_criteria: [
      { id: 'ac-003-1', parameter: 'Pressure decay rate', unit: 'PSI/hr', min: 0, max: 1.0 },
      { id: 'ac-003-2', parameter: 'Hold pressure', unit: 'PSI', min: 198, max: 202, nominal: 200 },
      { id: 'ac-003-3', parameter: 'Test duration', unit: 'min', min: 15, max: 60, nominal: 30 },
    ],
    status: 'active',
    created_at: '2025-03-10T10:00:00Z',
    updated_at: '2025-09-01T16:00:00Z',
  },
  {
    id: 'proto-004',
    name: 'Refrigerant Charge Verification',
    revision: 'B',
    owner: 'M. Torres',
    equipment_required: [
      'Refrigerant recovery/charging station',
      'Calibrated manifold gauge set',
      'Electronic scale (0.1 oz resolution)',
    ],
    fixture_required: 'FIX-004',
    acceptance_criteria: [
      { id: 'ac-004-1', parameter: 'Refrigerant charge weight', unit: 'oz', min: 14.5, max: 15.5, nominal: 15.0 },
      { id: 'ac-004-2', parameter: 'High side pressure (steady state)', unit: 'PSI', min: 210, max: 260 },
      { id: 'ac-004-3', parameter: 'Low side pressure (steady state)', unit: 'PSI', min: 55, max: 75 },
      { id: 'ac-004-4', parameter: 'Superheat at evap outlet', unit: 'F', min: 8, max: 18, nominal: 12 },
    ],
    status: 'active',
    created_at: '2025-01-20T11:00:00Z',
    updated_at: '2025-07-22T09:45:00Z',
  },
  {
    id: 'proto-005',
    name: 'Thermostat Response Time Test',
    revision: 'A',
    owner: 'R. Patel',
    equipment_required: [
      'Data logger (1 Hz minimum sample rate)',
      'Reference thermometer (Class 0.1)',
      'Variable load bank (0-15 A)',
    ],
    fixture_required: 'FIX-002',
    acceptance_criteria: [
      { id: 'ac-005-1', parameter: 'Setpoint accuracy', unit: 'F', min: -1.0, max: 1.0 },
      { id: 'ac-005-2', parameter: 'Cycle on delay', unit: 's', min: 0, max: 45 },
      { id: 'ac-005-3', parameter: 'Deadband width', unit: 'F', min: 2.0, max: 4.0, nominal: 3.0 },
    ],
    status: 'draft',
    created_at: '2025-10-01T14:00:00Z',
    updated_at: '2025-10-01T14:00:00Z',
  },
  {
    id: 'proto-006',
    name: 'Vibration Endurance Test',
    revision: 'D',
    owner: 'D. Kim',
    equipment_required: [
      'Electrodynamic shaker table (100 lbf minimum force)',
      'Triaxial accelerometer (IEPE, 100 mV/g)',
      'Vibration controller and power amplifier',
    ],
    fixture_required: 'FIX-005',
    acceptance_criteria: [
      { id: 'ac-006-1', parameter: 'Peak acceleration (X axis)', unit: 'g', min: 0, max: 2.5 },
      { id: 'ac-006-2', parameter: 'Peak acceleration (Y axis)', unit: 'g', min: 0, max: 2.5 },
      { id: 'ac-006-3', parameter: 'Peak acceleration (Z axis)', unit: 'g', min: 0, max: 3.0 },
      { id: 'ac-006-4', parameter: 'Test duration', unit: 'hr', min: 4, max: 4, nominal: 4 },
    ],
    status: 'archived',
    created_at: '2024-06-01T08:00:00Z',
    updated_at: '2025-05-30T10:00:00Z',
  },
]

export const MOCK_FIXTURES: Fixture[] = [
  {
    id: 'FIX-001',
    name: 'Hydraulic Pressure Bench A',
    type: 'Pressure Test',
    location: 'Bay 1',
    status: 'active',
    last_check_date: '2025-09-15',
    next_check_date: '2026-03-15',
    notes: 'Calibrated per ISO 4126. Annual calibration required. Certificate on file.',
    created_at: '2024-01-10T08:00:00Z',
    updated_at: '2025-09-15T10:00:00Z',
  },
  {
    id: 'FIX-002',
    name: 'Thermocouple Calibrator TC-500',
    type: 'Temperature Calibration',
    location: 'Lab A',
    status: 'active',
    last_check_date: '2025-11-01',
    next_check_date: '2026-05-01',
    notes: 'NIST traceable certificate on file. 6-month recalibration interval. Verify with check source before each use.',
    created_at: '2024-03-01T09:00:00Z',
    updated_at: '2025-11-01T14:00:00Z',
  },
  {
    id: 'FIX-003',
    name: 'Refrigerant Leak Detector RLD-200',
    type: 'Leak Detection',
    location: 'Bay 3',
    status: 'active',
    last_check_date: '2025-10-20',
    next_check_date: '2026-04-20',
    notes: 'Sensor replaced October 2025. Verify sensitivity with calibration gas before each test series.',
    created_at: '2024-02-15T11:00:00Z',
    updated_at: '2025-10-20T16:30:00Z',
  },
  {
    id: 'FIX-004',
    name: 'Refrigerant Recovery/Charging Station',
    type: 'Charging Station',
    location: 'Bay 2',
    status: 'inactive',
    last_check_date: '2025-04-10',
    next_check_date: '2025-10-10',
    notes: 'Decommissioned pending compressor repair. DO NOT USE until cleared by engineering.',
    created_at: '2023-11-05T08:00:00Z',
    updated_at: '2025-07-08T09:00:00Z',
  },
  {
    id: 'FIX-005',
    name: 'Environmental Chamber EC-400',
    type: 'Environmental Test',
    location: 'Lab B',
    status: 'under_maintenance',
    last_check_date: '2025-08-01',
    next_check_date: '2025-12-01',
    notes: 'Cooling coil replacement in progress. Expected return to service December 2025.',
    created_at: '2023-08-20T10:00:00Z',
    updated_at: '2025-11-05T08:30:00Z',
  },
]

export const MOCK_TEST_RUNS: TestRun[] = [
  {
    id: 'TR-0051',
    protocol_id: 'proto-001',
    protocol_revision: 'B',
    unit_id: 'PRV-2025-047',
    operator: 'J. Ochoa',
    fixture_id: 'FIX-001',
    date: '2025-11-12',
    measurements: [
      { criterion_id: 'ac-001-1', parameter: 'Relief pressure setpoint', value: 302, unit: 'PSI', within_spec: true },
      { criterion_id: 'ac-001-2', parameter: 'Reseat pressure', value: 272, unit: 'PSI', within_spec: true },
      { criterion_id: 'ac-001-3', parameter: 'Flow rate at setpoint', value: 3.1, unit: 'GPM', within_spec: true },
      { criterion_id: 'ac-001-4', parameter: 'Leak rate after reseat', value: 0.8, unit: 'mL/min', within_spec: true },
    ],
    result: 'pass',
    observations: 'Valve opened cleanly. No anomalous sounds during flow test. All parameters nominal.',
    created_at: '2025-11-12T09:30:00Z',
    updated_at: '2025-11-12T11:00:00Z',
  },
  {
    id: 'TR-0052',
    protocol_id: 'proto-001',
    protocol_revision: 'B',
    unit_id: 'PRV-2025-048',
    operator: 'J. Ochoa',
    fixture_id: 'FIX-001',
    date: '2025-11-12',
    measurements: [
      { criterion_id: 'ac-001-1', parameter: 'Relief pressure setpoint', value: 318, unit: 'PSI', within_spec: false },
      { criterion_id: 'ac-001-2', parameter: 'Reseat pressure', value: 278, unit: 'PSI', within_spec: true },
      { criterion_id: 'ac-001-3', parameter: 'Flow rate at setpoint', value: 2.7, unit: 'GPM', within_spec: true },
      { criterion_id: 'ac-001-4', parameter: 'Leak rate after reseat', value: 1.2, unit: 'mL/min', within_spec: true },
    ],
    result: 'fail',
    observations: 'Setpoint exceeded upper limit by 8 PSI. No visible damage. Sent to engineering for disposition.',
    created_at: '2025-11-12T11:30:00Z',
    updated_at: '2025-11-12T13:00:00Z',
  },
  {
    id: 'TR-0053',
    protocol_id: 'proto-002',
    protocol_revision: 'C',
    unit_id: 'TSNS-2025-022',
    operator: 'K. Washington',
    fixture_id: 'FIX-002',
    date: '2025-11-10',
    measurements: [
      { criterion_id: 'ac-002-1', parameter: 'Accuracy at -20 C', value: 0.2, unit: 'C', within_spec: true },
      { criterion_id: 'ac-002-2', parameter: 'Accuracy at 25 C', value: 0.1, unit: 'C', within_spec: true },
      { criterion_id: 'ac-002-3', parameter: 'Accuracy at 70 C', value: 0.4, unit: 'C', within_spec: true },
      { criterion_id: 'ac-002-4', parameter: 'Response time (63% step)', value: 18, unit: 's', within_spec: true },
    ],
    result: 'pass',
    observations: 'Passed all three temperature points. Response time well within limit.',
    created_at: '2025-11-10T10:00:00Z',
    updated_at: '2025-11-10T12:30:00Z',
  },
  {
    id: 'TR-0054',
    protocol_id: 'proto-003',
    protocol_revision: 'A',
    unit_id: 'COMP-2025-011',
    operator: 'J. Ochoa',
    fixture_id: 'FIX-003',
    date: '2025-11-08',
    measurements: [
      { criterion_id: 'ac-003-1', parameter: 'Pressure decay rate', value: 0.4, unit: 'PSI/hr', within_spec: true },
      { criterion_id: 'ac-003-2', parameter: 'Hold pressure', value: 200, unit: 'PSI', within_spec: true },
      { criterion_id: 'ac-003-3', parameter: 'Test duration', value: 30, unit: 'min', within_spec: true },
    ],
    result: 'pass',
    observations: 'No leaks detected. Pressure decay within acceptable limit. Unit cleared.',
    created_at: '2025-11-08T08:00:00Z',
    updated_at: '2025-11-08T09:30:00Z',
  },
  {
    id: 'TR-0055',
    protocol_id: 'proto-003',
    protocol_revision: 'A',
    unit_id: 'COMP-2025-012',
    operator: 'K. Washington',
    fixture_id: 'FIX-003',
    date: '2025-11-08',
    measurements: [
      { criterion_id: 'ac-003-1', parameter: 'Pressure decay rate', value: 3.8, unit: 'PSI/hr', within_spec: false },
      { criterion_id: 'ac-003-2', parameter: 'Hold pressure', value: 200, unit: 'PSI', within_spec: true },
      { criterion_id: 'ac-003-3', parameter: 'Test duration', value: 30, unit: 'min', within_spec: true },
    ],
    result: 'fail',
    observations: 'Leak detected at discharge port fitting. Confirmed with soap bubble test. Tagged for rework.',
    created_at: '2025-11-08T10:00:00Z',
    updated_at: '2025-11-08T11:30:00Z',
  },
  {
    id: 'TR-0056',
    protocol_id: 'proto-002',
    protocol_revision: 'C',
    unit_id: 'TSNS-2025-023',
    operator: 'K. Washington',
    fixture_id: 'FIX-002',
    date: '2025-11-05',
    measurements: [
      { criterion_id: 'ac-002-1', parameter: 'Accuracy at -20 C', value: -0.3, unit: 'C', within_spec: true },
      { criterion_id: 'ac-002-2', parameter: 'Accuracy at 25 C', value: 0.6, unit: 'C', within_spec: false },
      { criterion_id: 'ac-002-3', parameter: 'Accuracy at 70 C', value: 0.3, unit: 'C', within_spec: true },
      { criterion_id: 'ac-002-4', parameter: 'Response time (63% step)', value: 22, unit: 's', within_spec: true },
    ],
    result: 'fail',
    observations: 'Out of tolerance at 25 C. Possible sensor drift. Flagged for investigation.',
    created_at: '2025-11-05T09:00:00Z',
    updated_at: '2025-11-05T11:00:00Z',
  },
  {
    id: 'TR-0057',
    protocol_id: 'proto-001',
    protocol_revision: 'B',
    unit_id: 'PRV-2025-049',
    operator: 'M. Torres',
    fixture_id: 'FIX-001',
    date: '2025-11-03',
    measurements: [
      { criterion_id: 'ac-001-1', parameter: 'Relief pressure setpoint', value: 299, unit: 'PSI', within_spec: true },
      { criterion_id: 'ac-001-2', parameter: 'Reseat pressure', value: 265, unit: 'PSI', within_spec: true },
      { criterion_id: 'ac-001-3', parameter: 'Flow rate at setpoint', value: 3.4, unit: 'GPM', within_spec: true },
      { criterion_id: 'ac-001-4', parameter: 'Leak rate after reseat', value: 3.2, unit: 'mL/min', within_spec: true },
    ],
    result: 'pass',
    observations: '',
    created_at: '2025-11-03T14:00:00Z',
    updated_at: '2025-11-03T15:30:00Z',
  },
  {
    id: 'TR-0058',
    protocol_id: 'proto-004',
    protocol_revision: 'B',
    unit_id: 'REFU-2025-006',
    operator: 'M. Torres',
    fixture_id: 'FIX-004',
    date: '2025-10-28',
    measurements: [
      { criterion_id: 'ac-004-1', parameter: 'Refrigerant charge weight', value: 14.2, unit: 'oz', within_spec: false },
      { criterion_id: 'ac-004-2', parameter: 'High side pressure (steady state)', value: 190, unit: 'PSI', within_spec: false },
      { criterion_id: 'ac-004-3', parameter: 'Low side pressure (steady state)', value: 48, unit: 'PSI', within_spec: false },
      { criterion_id: 'ac-004-4', parameter: 'Superheat at evap outlet', value: 22, unit: 'F', within_spec: false },
    ],
    result: 'fail',
    observations: 'Undercharged unit. All pressures below spec. Possible slow leak or improper initial charge.',
    created_at: '2025-10-28T10:00:00Z',
    updated_at: '2025-10-28T12:00:00Z',
  },
  {
    id: 'TR-0059',
    protocol_id: 'proto-002',
    protocol_revision: 'C',
    unit_id: 'TSNS-2025-024',
    operator: 'J. Ochoa',
    fixture_id: 'FIX-002',
    date: '2025-10-25',
    measurements: [
      { criterion_id: 'ac-002-1', parameter: 'Accuracy at -20 C', value: 0.1, unit: 'C', within_spec: true },
      { criterion_id: 'ac-002-2', parameter: 'Accuracy at 25 C', value: -0.2, unit: 'C', within_spec: true },
      { criterion_id: 'ac-002-3', parameter: 'Accuracy at 70 C', value: 0.3, unit: 'C', within_spec: true },
      { criterion_id: 'ac-002-4', parameter: 'Response time (63% step)', value: 25, unit: 's', within_spec: true },
    ],
    result: 'pass',
    observations: '',
    created_at: '2025-10-25T11:00:00Z',
    updated_at: '2025-10-25T13:00:00Z',
  },
  {
    id: 'TR-0060',
    protocol_id: 'proto-003',
    protocol_revision: 'A',
    unit_id: 'COMP-2025-013',
    operator: 'D. Kim',
    fixture_id: 'FIX-003',
    date: '2025-10-20',
    measurements: [
      { criterion_id: 'ac-003-1', parameter: 'Pressure decay rate', value: 0.2, unit: 'PSI/hr', within_spec: true },
      { criterion_id: 'ac-003-2', parameter: 'Hold pressure', value: 201, unit: 'PSI', within_spec: true },
      { criterion_id: 'ac-003-3', parameter: 'Test duration', value: 30, unit: 'min', within_spec: true },
    ],
    result: 'pass',
    observations: 'Clean result. Unit cleared for shipment.',
    created_at: '2025-10-20T09:00:00Z',
    updated_at: '2025-10-20T10:30:00Z',
  },
  {
    id: 'TR-0061',
    protocol_id: 'proto-001',
    protocol_revision: 'B',
    unit_id: 'PRV-2025-050',
    operator: 'D. Kim',
    fixture_id: 'FIX-001',
    date: '2025-10-15',
    measurements: [
      { criterion_id: 'ac-001-1', parameter: 'Relief pressure setpoint', value: 305, unit: 'PSI', within_spec: true },
      { criterion_id: 'ac-001-2', parameter: 'Reseat pressure', value: 260, unit: 'PSI', within_spec: true },
      { criterion_id: 'ac-001-3', parameter: 'Flow rate at setpoint', value: 4.8, unit: 'GPM', within_spec: false },
      { criterion_id: 'ac-001-4', parameter: 'Leak rate after reseat', value: 0.5, unit: 'mL/min', within_spec: true },
    ],
    result: 'needs_review',
    observations: 'Flow rate exceeded upper limit by 0.3 GPM. Possibly related to bore wear. Engineering review required before disposition.',
    created_at: '2025-10-15T13:00:00Z',
    updated_at: '2025-10-15T15:00:00Z',
  },
]

export const MOCK_FAILURES: Failure[] = [
  {
    id: 'FAI-001',
    test_run_id: 'TR-0052',
    failure_mode: 'Relief setpoint out of tolerance - high',
    severity: 'major',
    suspected_cause: 'Spring preload shifted during handling. Possible misassembly at final torque step.',
    disposition: 'rework',
    corrective_action: 'Return to assembly for spring adjustment and re-torque. Retest per PRV-001 Rev B.',
    owner: 'M. Torres',
    status: 'closed',
    opened_date: '2025-11-12',
    closed_date: '2025-11-18',
    created_at: '2025-11-12T13:00:00Z',
    updated_at: '2025-11-18T10:00:00Z',
  },
  {
    id: 'FAI-002',
    test_run_id: 'TR-0055',
    failure_mode: 'Compressor leak at discharge port fitting',
    severity: 'critical',
    suspected_cause: 'Cracked discharge port fitting. Likely thermal stress fracture. Batch traceability initiated.',
    disposition: 'scrap',
    corrective_action: 'Unit scrapped. Fitting supplier notified. Incoming inspection tightened for this batch.',
    owner: 'D. Kim',
    status: 'in_progress',
    opened_date: '2025-11-08',
    closed_date: null,
    created_at: '2025-11-08T11:30:00Z',
    updated_at: '2025-11-20T09:00:00Z',
  },
  {
    id: 'FAI-003',
    test_run_id: 'TR-0056',
    failure_mode: 'Temperature sensor out of tolerance at 25 C',
    severity: 'major',
    suspected_cause: 'Sensor drift due to high humidity exposure during storage. Incoming QC gap identified.',
    disposition: 'scrap',
    corrective_action: 'Lot isolated. Storage conditions reviewed. 100% inspection on remaining sensors from this lot.',
    owner: 'R. Patel',
    status: 'open',
    opened_date: '2025-11-05',
    closed_date: null,
    created_at: '2025-11-05T11:00:00Z',
    updated_at: '2025-11-05T11:00:00Z',
  },
  {
    id: 'FAI-004',
    test_run_id: 'TR-0058',
    failure_mode: 'Low refrigerant charge - multiple parameters out of spec',
    severity: 'critical',
    suspected_cause: 'Undercharge during fill process. Scale calibration may have drifted. Operator error possible.',
    disposition: 'rework',
    corrective_action: 'Recover and recharge unit. Verify scale calibration. Operator retraining logged.',
    owner: 'M. Torres',
    status: 'closed',
    opened_date: '2025-10-28',
    closed_date: '2025-11-02',
    created_at: '2025-10-28T12:00:00Z',
    updated_at: '2025-11-02T14:00:00Z',
  },
  {
    id: 'FAI-005',
    test_run_id: 'TR-0061',
    failure_mode: 'Flow rate above upper limit - bore wear suspected',
    severity: 'minor',
    suspected_cause: 'Bore wear beyond tolerance. May indicate end of service life for this valve type.',
    disposition: 'pending',
    corrective_action: 'Pending engineering review. Valve held for dimensional inspection.',
    owner: 'D. Kim',
    status: 'open',
    opened_date: '2025-10-15',
    closed_date: null,
    created_at: '2025-10-15T15:00:00Z',
    updated_at: '2025-10-15T15:00:00Z',
  },
  {
    id: 'FAI-006',
    test_run_id: 'TR-0055',
    failure_mode: 'Compressor leak at suction port O-ring',
    severity: 'critical',
    suspected_cause: 'O-ring failure. Hardened O-ring likely from improper storage temperature.',
    disposition: 'rework',
    corrective_action: 'Replace O-ring. Inspect remaining units from this assembly batch.',
    owner: 'D. Kim',
    status: 'in_progress',
    opened_date: '2025-11-09',
    closed_date: null,
    created_at: '2025-11-09T09:00:00Z',
    updated_at: '2025-11-19T14:00:00Z',
  },
  {
    id: 'FAI-007',
    test_run_id: 'TR-0052',
    failure_mode: 'Relief setpoint out of tolerance - high',
    severity: 'major',
    suspected_cause: 'Same root cause as FAI-001. Spring preload issue confirmed systematic.',
    disposition: 'rework',
    corrective_action: 'Assembly procedure updated with torque verification step. Tooling inspection added.',
    owner: 'M. Torres',
    status: 'closed',
    opened_date: '2025-11-12',
    closed_date: '2025-11-19',
    created_at: '2025-11-12T14:00:00Z',
    updated_at: '2025-11-19T11:00:00Z',
  },
  {
    id: 'FAI-008',
    test_run_id: 'TR-0056',
    failure_mode: 'Temperature sensor out of tolerance at 25 C',
    severity: 'major',
    suspected_cause: 'Recurring failure mode from same sensor lot as FAI-003. Lot-level issue confirmed.',
    disposition: 'scrap',
    corrective_action: 'Additional units from lot quarantined. Supplier corrective action request issued.',
    owner: 'R. Patel',
    status: 'in_progress',
    opened_date: '2025-11-06',
    closed_date: null,
    created_at: '2025-11-06T09:00:00Z',
    updated_at: '2025-11-21T10:00:00Z',
  },
]
